import 'package:flutter/material.dart';
import '../theme/app_colors.dart';

class SkillInfo {
  final String name;
  final String description;

  const SkillInfo({
    required this.name,
    required this.description,
  });
}

class CategoryInfo {
  final String id;
  final String name;
  final String description;
  final List<SkillInfo> skills;
  final IconData icon;
  final Color color;

  const CategoryInfo({
    required this.id,
    required this.name,
    required this.description,
    required this.skills,
    required this.icon,
    required this.color,
  });
}

const List<CategoryInfo> allCategories = [
  CategoryInfo(
    id: '01',
    name: 'Home Services',
    description: 'Roz ke ghar ke kaam — cleaning se lekar repairs tak',
    icon: Icons.home_repair_service_outlined,
    color: AppColors.highlightPink,
    skills: [
      SkillInfo(name: 'Plumber', description: 'Nali, pipe, bore, leakage fix'),
      SkillInfo(name: 'Electrician', description: 'Wiring, fitting, MCB, fan repair'),
      SkillInfo(name: 'Carpenter', description: 'Furniture banao, repair karo, polish'),
      SkillInfo(name: 'Painter', description: 'Wall paint, texture, waterproofing'),
      SkillInfo(name: 'AC Technician', description: 'AC service, gas filling, repair'),
      SkillInfo(name: 'Refrigerator Repair', description: 'Fridge, washing machine repair'),
      SkillInfo(name: 'TV / Electronics Repair', description: 'LED, CRT, home theatre repair'),
      SkillInfo(name: 'Pest Control', description: 'Cockroach, termite, mosquito treatment'),
      SkillInfo(name: 'Deep Cleaning', description: 'Kitchen, bathroom, full home deep clean'),
      SkillInfo(name: 'House Cleaning (Daily)', description: 'Jhadu, pocha, dusting — roz'),
      SkillInfo(name: 'Sofa / Carpet Cleaning', description: 'Dry clean, steam cleaning'),
      SkillInfo(name: 'Water Tank Cleaning', description: 'Underground aur overhead tank'),
      SkillInfo(name: 'RO / Water Purifier Repair', description: 'RO servicing aur repair'),
      SkillInfo(name: 'Gas Stove Repair', description: 'Burner, regulator, pipeline fix'),
      SkillInfo(name: 'CCTV Installation', description: 'Camera fitting, DVR setup, wiring'),
      SkillInfo(name: 'False Ceiling Work', description: 'POP, gypsum ceiling installation'),
      SkillInfo(name: 'Tiles / Flooring Work', description: 'Tiles fitting, marble polish'),
      SkillInfo(name: 'Waterproofing', description: 'Roof, bathroom, basement waterproofing'),
      SkillInfo(name: 'Modular Kitchen Work', description: 'Cabinet fitting, chimney install'),
      SkillInfo(name: 'Interior Designer', description: 'Home decor, space planning, 3D design'),
    ],
  ),
  CategoryInfo(
    id: '02',
    name: 'Education & Tutoring',
    description: 'Ghar par tuition, coaching aur skill classes',
    icon: Icons.school_outlined,
    color: AppColors.highlightGreen,
    skills: [
      SkillInfo(name: 'Maths Tutor', description: 'Class 1 se 12 tak, JEE/NEET prep'),
      SkillInfo(name: 'Science Tutor', description: 'Physics, Chemistry, Biology'),
      SkillInfo(name: 'English Tutor', description: 'Spoken English, grammar, writing'),
      SkillInfo(name: 'Hindi Tutor', description: 'Hindi medium students ke liye'),
      SkillInfo(name: 'Computer Tutor', description: 'MS Office, typing, basic computer'),
      SkillInfo(name: 'Music Teacher (Vocal)', description: 'Hindustani classical, filmi singing'),
      SkillInfo(name: 'Guitar Teacher', description: 'Acoustic, electric, bass guitar'),
      SkillInfo(name: 'Tabla / Dholak Teacher', description: 'Classical percussion instruments'),
      SkillInfo(name: 'Dance Teacher (Classical)', description: 'Kathak, Bharatanatyam, Kuchipudi'),
      SkillInfo(name: 'Dance Teacher (Bollywood)', description: 'Bollywood, hip-hop, freestyle'),
      SkillInfo(name: 'Drawing & Art Teacher', description: 'Sketch, watercolor, acrylic'),
      SkillInfo(name: 'Yoga Teacher', description: 'Hatha, Vinyasa, meditation'),
      SkillInfo(name: 'Spoken English Coach', description: 'Communication, accent training'),
      SkillInfo(name: 'UPSC / Govt Exam Coach', description: 'GS, current affairs, strategy'),
      SkillInfo(name: 'Coding Teacher (Kids)', description: 'Scratch, Python basics for children'),
      SkillInfo(name: 'Abacus / Vedic Math', description: 'Mental math speed training'),
      SkillInfo(name: 'Primary Class Teacher', description: 'LKG to class 5 all subjects'),
      SkillInfo(name: 'Sanskrit Tutor', description: 'Classical Sanskrit, shlokas'),
      SkillInfo(name: 'Urdu Tutor', description: 'Urdu reading, writing, calligraphy'),
      SkillInfo(name: 'Chess Coach', description: 'Beginner to advanced chess training'),
    ],
  ),
  CategoryInfo(
    id: '03',
    name: 'Beauty & Wellness',
    description: 'Ghar par beauty, grooming aur wellness services',
    icon: Icons.face_retouching_natural_outlined,
    color: AppColors.highlightBlue,
    skills: [
      SkillInfo(name: 'Mehendi Artist', description: 'Bridal mehendi, Arabic, geometric'),
      SkillInfo(name: 'Makeup Artist', description: 'Bridal, party, editorial makeup'),
      SkillInfo(name: 'Parlour at Home (Ladies)', description: 'Facial, waxing, threading, cleanup'),
      SkillInfo(name: 'Hair Stylist', description: 'Haircut, color, smoothening, keratin'),
      SkillInfo(name: 'Nail Artist', description: 'Nail extension, gel nails, nail art'),
      SkillInfo(name: 'Eyebrow Shaping', description: 'Threading, waxing, microblading'),
      SkillInfo(name: 'Massage Therapist', description: 'Body massage, head massage, spa'),
      SkillInfo(name: 'Pedicure / Manicure', description: 'Basic to premium nail care'),
      SkillInfo(name: 'Barber (Men\'s Grooming)', description: 'Haircut, shave, beard styling'),
      SkillInfo(name: 'Skin Care Specialist', description: 'Acne treatment, facials, peels'),
      SkillInfo(name: 'Waxing Specialist', description: 'Full body, face, Brazilian wax'),
      SkillInfo(name: 'Eyebrow Tattooing', description: 'Microblading, powder brows, ombre'),
      SkillInfo(name: 'Eyelash Extension', description: 'Classic, volume, hybrid lashes'),
      SkillInfo(name: 'Bridal Package Artist', description: 'Full bridal preparation package'),
      SkillInfo(name: 'Salwar Suit Stitching', description: 'Custom stitching, alteration'),
      SkillInfo(name: 'Saree Draping', description: 'Event saree draping, bridal draping'),
      SkillInfo(name: 'Hair Spa Specialist', description: 'Oil massage, protein treatment'),
      SkillInfo(name: 'Henna Cone Making', description: 'Fresh mehendi cone preparation'),
      SkillInfo(name: 'Body Polishing', description: 'Full body scrub and polishing treatment'),
      SkillInfo(name: 'Foot Reflexology', description: 'Pressure point foot massage therapy'),
    ],
  ),
  CategoryInfo(
    id: '04',
    name: 'Tailoring & Fashion',
    description: 'Kapde silna, badalna aur fashion design',
    icon: Icons.style_outlined,
    color: AppColors.accent,
    skills: [
      SkillInfo(name: 'Ladies Tailor (Darzi)', description: 'Salwar, blouse, kurti, suit stitching'),
      SkillInfo(name: 'Gents Tailor', description: 'Shirt, pant, sherwani, kurta stitching'),
      SkillInfo(name: 'Blouse Stitching', description: 'Designer blouse, back neck work'),
      SkillInfo(name: 'Saree Fall & Pico', description: 'Fall laga, pico karo, saree work'),
      SkillInfo(name: 'Alteration Specialist', description: 'Fitting alter, size change, repair'),
      SkillInfo(name: 'Embroidery Artist', description: 'Zari, gota, thread work, machine'),
      SkillInfo(name: 'Fabric Painter', description: 'Block print, hand paint on fabric'),
      SkillInfo(name: 'Knitting / Crochet', description: 'Sweater, muffler, baby clothes'),
      SkillInfo(name: 'Bag Making', description: 'Canvas, jute, leather bag stitching'),
      SkillInfo(name: 'Curtain / Cushion Maker', description: 'Home furnishing stitching work'),
      SkillInfo(name: 'Lehenga Design Work', description: 'Bridal lehenga customization'),
      SkillInfo(name: 'Children\'s Clothes', description: 'Baby & kids custom clothing'),
      SkillInfo(name: 'Uniform Stitching', description: 'School, office, corporate uniform'),
      SkillInfo(name: 'Leather Work', description: 'Belt, wallet, shoes, bag repair'),
      SkillInfo(name: 'Tie & Dye Artist', description: 'Bandhani, shibori, batik printing'),
      SkillInfo(name: 'Aari Work', description: 'Zardosi, aari embroidery on fabric'),
      SkillInfo(name: 'Dress Designer', description: 'Fashion design, pattern making'),
      SkillInfo(name: 'Saree to Lehenga Convert', description: 'Saree conversion alterations'),
      SkillInfo(name: 'Suit Repair & Repatch', description: 'Torn, burned fabric repair'),
      SkillInfo(name: 'Crochet Jewelry', description: 'Thread jewelry, crochet accessories'),
    ],
  ),
  CategoryInfo(
    id: '05',
    name: 'Food & Catering',
    description: 'Ghar ka khana, catering aur baking services',
    icon: Icons.restaurant_outlined,
    color: AppColors.highlightPink,
    skills: [
      SkillInfo(name: 'Home Cook (Daily)', description: 'Regular ghar ka khana banana'),
      SkillInfo(name: 'Tiffin Service', description: 'Daily dabba service, meal prep'),
      SkillInfo(name: 'Event Catering', description: 'Shaadi, party, function catering'),
      SkillInfo(name: 'Cake Baker', description: 'Custom cakes, cupcakes, fondant'),
      SkillInfo(name: 'Mithai Maker', description: 'Homemade sweets, barfi, ladoo'),
      SkillInfo(name: 'Pickle Maker', description: 'Achaar, murabba, homemade pickles'),
      SkillInfo(name: 'Tandoor Specialist', description: 'Tandoori roti, naan, chicken'),
      SkillInfo(name: 'Biryani Specialist', description: 'Dum biryani, pulao cooking'),
      SkillInfo(name: 'South Indian Cook', description: 'Idli, dosa, sambar, uttapam'),
      SkillInfo(name: 'Chinese Cook', description: 'Hakka noodles, fried rice, manchurian'),
      SkillInfo(name: 'Continental Chef', description: 'Pasta, salads, continental cuisine'),
      SkillInfo(name: 'Jain / Satvik Cook', description: 'No onion-garlic pure veg cooking'),
      SkillInfo(name: 'Dietitian Meal Prep', description: 'Healthy, calorie-counted meals'),
      SkillInfo(name: 'Papad / Wafer Maker', description: 'Homemade papad, chips, farsan'),
      SkillInfo(name: 'Jam / Jelly Maker', description: 'Fruit jam, marmalade, preserves'),
      SkillInfo(name: 'Bakery Products', description: 'Bread, cookies, muffins baking'),
      SkillInfo(name: 'Chaat / Street Food', description: 'Pani puri, bhel, sev puri events'),
      SkillInfo(name: 'Dry Fruit Mithai', description: 'Premium dry fruit sweets'),
      SkillInfo(name: 'Non-Veg Specialist', description: 'Fish, mutton, chicken curries'),
      SkillInfo(name: 'Breakfast Specialist', description: 'Paratha, poha, upma, breakfast items'),
    ],
  ),
  CategoryInfo(
    id: '06',
    name: 'Events & Decoration',
    description: 'Shaadi, birthday aur events ka decoration',
    icon: Icons.celebration_outlined,
    color: AppColors.highlightGreen,
    skills: [
      SkillInfo(name: 'Wedding Decorator', description: 'Mandap, stage, floral decoration'),
      SkillInfo(name: 'Birthday Decorator', description: 'Balloon, theme party decoration'),
      SkillInfo(name: 'Balloon Artist', description: 'Balloon arch, twisting, sculptures'),
      SkillInfo(name: 'Flower Decorator', description: 'Fresh flower rangoli, gate, mandap'),
      SkillInfo(name: 'Rangoli Artist', description: 'Dry color, floral, LED rangoli'),
      SkillInfo(name: 'Mehndi Decorator', description: 'Mehndi rasam decoration, setup'),
      SkillInfo(name: 'DJ / Sound Setup', description: 'Speaker, DJ console, sound mixing'),
      SkillInfo(name: 'Photography', description: 'Event, wedding, portrait photography'),
      SkillInfo(name: 'Videography', description: 'Wedding films, reels, drone video'),
      SkillInfo(name: 'Photo Editing', description: 'Wedding album editing, retouching'),
      SkillInfo(name: 'Tent / Canopy Setup', description: 'Shamiana, tent, outdoor setup'),
      SkillInfo(name: 'Caricature Artist', description: 'Live drawing at events, parties'),
      SkillInfo(name: 'Emcee / Anchor', description: 'Event hosting, MC for functions'),
      SkillInfo(name: 'Band / Baaja Player', description: 'Brass band, dhol, shehnai'),
      SkillInfo(name: 'Haldi Decoration', description: 'Floral haldi setup, photography'),
      SkillInfo(name: 'Baby Shower Setup', description: 'Theme decoration, games, setup'),
      SkillInfo(name: 'Corporate Event Setup', description: 'Office party, conference decor'),
      SkillInfo(name: 'Lighting Setup', description: 'Fairy lights, LED, uplighting'),
      SkillInfo(name: 'Invitation Card Maker', description: 'Custom digital & print cards'),
      SkillInfo(name: 'Fireworks Handler', description: 'Licensed fireworks for events'),
    ],
  ),
  CategoryInfo(
    id: '07',
    name: 'Health & Fitness',
    description: 'Personal trainer, yoga, physiotherapy at home',
    icon: Icons.fitness_center_outlined,
    color: AppColors.highlightBlue,
    skills: [
      SkillInfo(name: 'Personal Trainer', description: 'Home gym, weight loss, muscle gain'),
      SkillInfo(name: 'Yoga Instructor', description: 'Hatha, Ashtanga, prenatal yoga'),
      SkillInfo(name: 'Zumba Instructor', description: 'Dance fitness, Bollywood Zumba'),
      SkillInfo(name: 'Physiotherapist', description: 'Joint pain, injury rehab, therapy'),
      SkillInfo(name: 'Nutritionist', description: 'Diet plan, weight management, advice'),
      SkillInfo(name: 'Meditation Coach', description: 'Guided meditation, mindfulness'),
      SkillInfo(name: 'Karate / Martial Arts', description: 'Self-defense training for all ages'),
      SkillInfo(name: 'Swimming Coach', description: 'Learn swimming, technique coaching'),
      SkillInfo(name: 'Aerobics Instructor', description: 'Group aerobics, cardio classes'),
      SkillInfo(name: 'Badminton Coach', description: 'Beginner to advanced coaching'),
      SkillInfo(name: 'Cricket Coaching', description: 'Batting, bowling, fielding drills'),
      SkillInfo(name: 'Football Coaching', description: 'Kids and youth football training'),
      SkillInfo(name: 'Cycling Coach', description: 'Road cycling, MTB technique'),
      SkillInfo(name: 'Boxing Coach', description: 'Fitness boxing, technique training'),
      SkillInfo(name: 'Crossfit Trainer', description: 'WOD programming, technique'),
      SkillInfo(name: 'Pilates Instructor', description: 'Core strength, flexibility training'),
      SkillInfo(name: 'Sports Rehabilitation', description: 'Injury recovery, sports physio'),
      SkillInfo(name: 'Senior Fitness Trainer', description: 'Exercise for elderly, mobility'),
      SkillInfo(name: 'Kids Fitness Trainer', description: 'Fun fitness activities for children'),
      SkillInfo(name: 'Pranayama Teacher', description: 'Breathing exercises, kapalbhati'),
    ],
  ),
  CategoryInfo(
    id: '08',
    name: 'Technology & IT',
    description: 'Computer, phone, network aur IT support',
    icon: Icons.devices_outlined,
    color: AppColors.accent,
    skills: [
      SkillInfo(name: 'Computer Repair', description: 'Hardware fix, virus removal, upgrade'),
      SkillInfo(name: 'Laptop Repair', description: 'Screen, keyboard, battery, motherboard'),
      SkillInfo(name: 'Mobile Repair', description: 'Screen, battery, charging port fix'),
      SkillInfo(name: 'Printer Repair', description: 'Ink, head cleaning, hardware fix'),
      SkillInfo(name: 'WiFi / Network Setup', description: 'Router, mesh, cable networking'),
      SkillInfo(name: 'CCTV & Security Setup', description: 'IP camera, NVR, remote access'),
      SkillInfo(name: 'Smart Home Setup', description: 'Alexa, Google Home, automation'),
      SkillInfo(name: 'Web Developer', description: 'WordPress, e-commerce, custom site'),
      SkillInfo(name: 'App Developer', description: 'Mobile app development, Flutter'),
      SkillInfo(name: 'Graphic Designer', description: 'Logo, banner, social media design'),
      SkillInfo(name: 'Data Entry Operator', description: 'Excel, form filling, typing work'),
      SkillInfo(name: 'Tally / Accounting', description: 'Tally ERP, GST filing, accounts'),
      SkillInfo(name: 'Social Media Manager', description: 'Instagram, Facebook page management'),
      SkillInfo(name: 'Video Editor', description: 'YouTube videos, reels, Premiere Pro'),
      SkillInfo(name: 'Photo Editor', description: 'Product photos, portraits, Photoshop'),
      SkillInfo(name: 'SEO Specialist', description: 'Google ranking, website traffic'),
      SkillInfo(name: 'Content Writer', description: 'Blog, product description, copywriting'),
      SkillInfo(name: 'Cybersecurity Help', description: 'Password safety, antivirus setup'),
      SkillInfo(name: 'Software Trainer', description: 'MS Office, Tally, Photoshop training'),
      SkillInfo(name: 'Cloud Setup Helper', description: 'Google Drive, OneDrive, backup'),
    ],
  ),
  CategoryInfo(
    id: '09',
    name: 'Pet Care',
    description: 'Pet grooming, training aur care services',
    icon: Icons.pets_outlined,
    color: AppColors.highlightPink,
    skills: [
      SkillInfo(name: 'Dog Groomer', description: 'Bath, haircut, nail clipping, ears'),
      SkillInfo(name: 'Cat Groomer', description: 'Cat bathing, brushing, nail trimming'),
      SkillInfo(name: 'Pet Trainer (Dog)', description: 'Basic commands, potty training'),
      SkillInfo(name: 'Pet Walker', description: 'Daily dog walking service'),
      SkillInfo(name: 'Pet Sitter', description: 'Home pet sitting while you travel'),
      SkillInfo(name: 'Pet Boarding', description: 'Safe pet stay at worker\'s home'),
      SkillInfo(name: 'Vet at Home', description: 'Basic checkup, vaccination, advice'),
      SkillInfo(name: 'Pet Photographer', description: 'Cute pet photo shoot at home'),
      SkillInfo(name: 'Aquarium Setup & Care', description: 'Fish tank setup, maintenance'),
      SkillInfo(name: 'Bird Cage Cleaning', description: 'Parrot, canary, love bird care'),
      SkillInfo(name: 'Pet Food Maker', description: 'Homemade healthy pet food prep'),
      SkillInfo(name: 'Rabbit / Guinea Pig Care', description: 'Small animal grooming, care'),
      SkillInfo(name: 'Pet Dental Cleaning', description: 'Dog teeth brushing, oral care'),
      SkillInfo(name: 'Flea Treatment', description: 'Anti-tick, anti-flea treatment'),
      SkillInfo(name: 'Pet First Aid', description: 'Emergency first aid for pets'),
      SkillInfo(name: 'Horse Grooming', description: 'Rural areas — horse care service'),
      SkillInfo(name: 'Cow / Buffalo Care', description: 'Dairy animal health, grooming'),
      SkillInfo(name: 'Goat Farming Help', description: 'Small scale goat farming guidance'),
      SkillInfo(name: 'Pet Transport', description: 'Safe pet taxi service'),
      SkillInfo(name: 'Pet Birthday Planner', description: 'Pet party decoration & cake'),
    ],
  ),
  CategoryInfo(
    id: '10',
    name: 'Transport & Logistics',
    description: 'Driver, delivery aur shifting services',
    icon: Icons.local_shipping_outlined,
    color: AppColors.highlightGreen,
    skills: [
      SkillInfo(name: 'Personal Driver', description: 'Car driver for daily use, outstation'),
      SkillInfo(name: 'Truck Driver', description: 'Goods transport, local/outstation'),
      SkillInfo(name: 'Auto Driver', description: 'Scheduled auto service'),
      SkillInfo(name: 'Bike Delivery', description: 'Local delivery, courier, food'),
      SkillInfo(name: 'Packers & Movers', description: 'Home shifting, office relocation'),
      SkillInfo(name: 'Furniture Moving', description: 'Heavy item moving, assembly'),
      SkillInfo(name: 'Car Mechanic', description: 'Engine, brake, service, AC regas'),
      SkillInfo(name: 'Bike Mechanic', description: 'Engine, tyre, chain, battery'),
      SkillInfo(name: 'Car Washer', description: 'Daily car cleaning, wax polish'),
      SkillInfo(name: 'Tyre Puncture Repair', description: 'Mobile puncture repair service'),
      SkillInfo(name: 'Outstation Driver', description: 'Long route, highway driving'),
      SkillInfo(name: 'School Van Driver', description: 'Safe kids school transport'),
      SkillInfo(name: 'E-Vehicle Technician', description: 'EV battery, motor, charging fix'),
      SkillInfo(name: 'Forklift Operator', description: 'Warehouse, factory operations'),
      SkillInfo(name: 'Rickshaw Puller (Electric)', description: 'E-rickshaw city transport'),
      SkillInfo(name: 'Delivery Partner Help', description: 'Zomato, Swiggy onboarding help'),
      SkillInfo(name: 'Courier Help', description: 'Last mile delivery assistance'),
      SkillInfo(name: 'Airport Cab Driver', description: 'Fixed rate airport transfer'),
      SkillInfo(name: 'Car Detailing', description: 'Deep car cleaning, ceramic coat'),
      SkillInfo(name: 'Denting & Painting', description: 'Car body repair and paint job'),
    ],
  ),
  CategoryInfo(
    id: '11',
    name: 'Agriculture & Rural',
    description: 'Kheti, bagwani aur rural kaam',
    icon: Icons.agriculture_outlined,
    color: AppColors.highlightBlue,
    skills: [
      SkillInfo(name: 'Tractor Operator', description: 'Ploughing, harvesting, transport'),
      SkillInfo(name: 'Irrigation Technician', description: 'Drip, sprinkler system setup'),
      SkillInfo(name: 'Crop Advisor', description: 'Soil health, crop selection, advice'),
      SkillInfo(name: 'Pesticide Sprayer', description: 'Manual & drone pesticide spraying'),
      SkillInfo(name: 'Horticulturist', description: 'Fruit, vegetable garden planning'),
      SkillInfo(name: 'Kitchen Garden Setup', description: 'Terrace/balcony garden setup'),
      SkillInfo(name: 'Nursery Worker', description: 'Plant care, sapling preparation'),
      SkillInfo(name: 'Tree Cutting / Trimming', description: 'Safe tree pruning, removal'),
      SkillInfo(name: 'Lawn Mowing', description: 'Garden maintenance, grass cutting'),
      SkillInfo(name: 'Flower Garden Setup', description: 'Home garden design and planting'),
      SkillInfo(name: 'Composting Expert', description: 'Vermicompost, organic waste mgmt'),
      SkillInfo(name: 'Beekeeper', description: 'Honey production, bee colony mgmt'),
      SkillInfo(name: 'Mushroom Farming', description: 'Oyster mushroom cultivation help'),
      SkillInfo(name: 'Vertical Garden Setup', description: 'Indoor plant walls, green walls'),
      SkillInfo(name: 'Landscape Designer', description: 'Garden design, pathway, ponds'),
      SkillInfo(name: 'Water Pump Repair', description: 'Submersible, monoblock pump fix'),
      SkillInfo(name: 'Well Digging', description: 'Hand pump and well construction'),
      SkillInfo(name: 'Cold Storage Help', description: 'Produce storage, temperature mgmt'),
      SkillInfo(name: 'Seed Treatment Expert', description: 'Seed priming, dressing methods'),
      SkillInfo(name: 'Organic Farming Guide', description: 'Natural farming consultation'),
    ],
  ),
  CategoryInfo(
    id: '12',
    name: 'Creative & Arts',
    description: 'Art, craft, photography aur creative services',
    icon: Icons.brush_outlined,
    color: AppColors.accent,
    skills: [
      SkillInfo(name: 'Portrait Painter', description: 'Oil, acrylic, watercolor portraits'),
      SkillInfo(name: 'Wall Mural Artist', description: 'Home, office wall painting/mural'),
      SkillInfo(name: 'Sketch Artist', description: 'Pencil sketch, charcoal portraits'),
      SkillInfo(name: 'Calligrapher', description: 'Hindi, Urdu, English calligraphy'),
      SkillInfo(name: 'Pottery Artist', description: 'Clay pot making, wheel throwing'),
      SkillInfo(name: 'Puppet Maker', description: 'Glove puppet, string puppet craft'),
      SkillInfo(name: 'Madhubani Painter', description: 'Traditional Bihar folk art'),
      SkillInfo(name: 'Warli Art', description: 'Tribal art on walls, canvas, fabric'),
      SkillInfo(name: 'Lippan Art', description: 'Mirror work clay art from Gujarat'),
      SkillInfo(name: 'Mandala Artist', description: 'Paper, canvas, wall mandala art'),
      SkillInfo(name: 'Candle Maker', description: 'Scented, decorative handmade candles'),
      SkillInfo(name: 'Soap Maker', description: 'Handmade natural soaps, bath bombs'),
      SkillInfo(name: 'Macrame Artist', description: 'Wall hangings, plant hangers'),
      SkillInfo(name: 'Origami / Paper Craft', description: 'Paper folding art and crafts'),
      SkillInfo(name: 'Resin Art', description: 'Resin jewelry, coasters, wall art'),
      SkillInfo(name: 'Terracotta Jewelry', description: 'Handmade clay jewelry design'),
      SkillInfo(name: 'Block Printing', description: 'Fabric and paper block printing'),
      SkillInfo(name: 'Weaving Artist', description: 'Handloom weaving, fabric craft'),
      SkillInfo(name: 'Glass Painting', description: 'Decorative glass art for home'),
      SkillInfo(name: 'Leather Craft', description: 'Custom leather goods handmade'),
    ],
  ),
  CategoryInfo(
    id: '13',
    name: 'Child Care & Elderly',
    description: 'Bachon aur buzurgon ki dekhbhal',
    icon: Icons.child_care_outlined,
    color: AppColors.highlightPink,
    skills: [
      SkillInfo(name: 'Baby Sitter', description: 'Infant and toddler care at home'),
      SkillInfo(name: 'Nanny / Ayah', description: 'Full time child care, feeding'),
      SkillInfo(name: 'Creche at Home', description: 'Home daycare for working parents'),
      SkillInfo(name: 'Old Age Care (Female)', description: 'Female caregiver for elderly ladies'),
      SkillInfo(name: 'Old Age Care (Male)', description: 'Male attendant for elderly gents'),
      SkillInfo(name: 'Patient Attendant', description: 'Hospital, home nursing attendant'),
      SkillInfo(name: 'Nurse (Home Visit)', description: 'Injection, dressing, BP checkup'),
      SkillInfo(name: 'Physiotherapy (Home)', description: 'Home physiotherapy sessions'),
      SkillInfo(name: 'Special Needs Care', description: 'Autism, CP, special children care'),
      SkillInfo(name: 'Night Duty Attendant', description: 'Overnight patient care'),
      SkillInfo(name: 'Newborn Baby Care', description: 'Newborn bathing, massage, feeding'),
      SkillInfo(name: 'Post-Surgery Care', description: 'Home recovery after surgery'),
      SkillInfo(name: 'Mental Health Support', description: 'Companionship for lonely elderly'),
      SkillInfo(name: 'Diabetic Care', description: 'Sugar monitoring, foot care'),
      SkillInfo(name: 'Wheelchair Helper', description: 'Mobility assistance, outings'),
      SkillInfo(name: 'Speech Therapy (Home)', description: 'Language, stuttering therapy'),
      SkillInfo(name: 'Occupational Therapy', description: 'Daily living skills therapy'),
      SkillInfo(name: 'Dementia Care', description: 'Alzheimer and dementia patient care'),
      SkillInfo(name: 'Palliative Care', description: 'End of life comfort and support'),
      SkillInfo(name: 'Cook for Elderly', description: 'Soft, healthy meals for seniors'),
    ],
  ),
  CategoryInfo(
    id: '14',
    name: 'Construction & Renovation',
    description: 'Ghar banana, todna aur renovation kaam',
    icon: Icons.construction_outlined,
    color: AppColors.highlightGreen,
    skills: [
      SkillInfo(name: 'Mason / Raj Mistri', description: 'Brick wall, plaster, cement work'),
      SkillInfo(name: 'Bar Bender (Rod Work)', description: 'Steel reinforcement, slab work'),
      SkillInfo(name: 'Shuttering Carpenter', description: 'Formwork, centering for slab'),
      SkillInfo(name: 'Welder', description: 'Arc, MIG, TIG welding work'),
      SkillInfo(name: 'Plumbing Fitter', description: 'New construction plumbing'),
      SkillInfo(name: 'Electrical Fitter', description: 'New wiring, switchboard fitting'),
      SkillInfo(name: 'Tile Fitter', description: 'Wall, floor, bathroom tile work'),
      SkillInfo(name: 'POP Mistri', description: 'Gypsum, POP false ceiling work'),
      SkillInfo(name: 'Glass Fitter', description: 'Window, door glass installation'),
      SkillInfo(name: 'Aluminum Fabricator', description: 'Window, door, partition work'),
      SkillInfo(name: 'Waterproofing Expert', description: 'Roof slab, bathroom proofing'),
      SkillInfo(name: 'Demolition Worker', description: 'Safe structure demolition'),
      SkillInfo(name: 'Excavator Operator', description: 'JCB, excavation for foundation'),
      SkillInfo(name: 'Concrete Mixer', description: 'RMC, concrete preparation'),
      SkillInfo(name: 'Grille / Gate Maker', description: 'Iron, MS grille fabrication'),
      SkillInfo(name: 'Wood Polish Worker', description: 'Furniture polish, lacquer, PU'),
      SkillInfo(name: 'Gypsum Board Worker', description: 'Partition wall, grid ceiling'),
      SkillInfo(name: 'Stone Mason', description: 'Stone cladding, natural stone work'),
      SkillInfo(name: 'Shed Builder', description: 'Iron, bamboo shed construction'),
      SkillInfo(name: 'Bamboo Craftsman', description: 'Bamboo furniture, structure build'),
    ],
  ),
  CategoryInfo(
    id: '15',
    name: 'Religious & Cultural',
    description: 'Puja, katha, cultural programs ke liye',
    icon: Icons.spa_outlined,
    color: AppColors.highlightBlue,
    skills: [
      SkillInfo(name: 'Pandit / Purohit', description: 'Puja, havan, vivah, grihapravesh'),
      SkillInfo(name: 'Katha Vachak', description: 'Ram katha, Bhagwat katha pravachan'),
      SkillInfo(name: 'Harmonium Player', description: 'Bhajan, kirtan sangat'),
      SkillInfo(name: 'Tabla Player', description: 'Classical, bhajan tabla sangat'),
      SkillInfo(name: 'Bhajan Singer', description: 'Devotional singing for events'),
      SkillInfo(name: 'Rangoli Artist (Festive)', description: 'Navratri, Diwali, festival rangoli'),
      SkillInfo(name: 'Idol Maker (Clay)', description: 'Clay Ganesh, Durga idol making'),
      SkillInfo(name: 'Maala Maker', description: 'Flower garland, puja maala'),
      SkillInfo(name: 'Havan Samagri Expert', description: 'Puja material preparation'),
      SkillInfo(name: 'Qawwali Singer', description: 'Sufi music, qawwali performance'),
      SkillInfo(name: 'Church Choir Singer', description: 'Christian devotional music'),
      SkillInfo(name: 'Gurudwara Seva', description: 'Langar preparation, gurdwara help'),
      SkillInfo(name: 'Astrologer', description: 'Kundali, jyotish, vastu shastra'),
      SkillInfo(name: 'Vastu Expert', description: 'Vastu consultation for home/office'),
      SkillInfo(name: 'Numerologist', description: 'Lucky number, name analysis'),
      SkillInfo(name: 'Tarot Card Reader', description: 'Life guidance, tarot reading'),
      SkillInfo(name: 'Folk Singer', description: 'Dholak songs, lok geet, birha'),
      SkillInfo(name: 'Nautanki Performer', description: 'Traditional UP folk performance'),
      SkillInfo(name: 'Puppet Show Artist', description: 'Kathputli for events, fairs'),
      SkillInfo(name: 'Cultural Costume Maker', description: 'Traditional dress stitching'),
    ],
  ),
];

IconData getCategoryIcon(String categoryName) {
  for (final cat in allCategories) {
    if (cat.name.toLowerCase() == categoryName.toLowerCase()) {
      return cat.icon;
    }
  }
  // Fallbacks
  final lower = categoryName.toLowerCase();
  if (lower.contains('tutor') || lower.contains('teach')) return Icons.school_outlined;
  if (lower.contains('plumb')) return Icons.home_repair_service_outlined;
  if (lower.contains('electric')) return Icons.flash_on_outlined;
  if (lower.contains('mehendi')) return Icons.face_retouching_natural_outlined;
  if (lower.contains('cook') || lower.contains('food') || lower.contains('chef')) return Icons.restaurant_outlined;
  if (lower.contains('tech') || lower.contains('computer') || lower.contains('it') || lower.contains('app') || lower.contains('web')) return Icons.devices_outlined;
  if (lower.contains('pet')) return Icons.pets_outlined;
  if (lower.contains('driver') || lower.contains('transport') || lower.contains('cab')) return Icons.local_shipping_outlined;
  if (lower.contains('creative') || lower.contains('art') || lower.contains('paint')) return Icons.brush_outlined;
  return Icons.person_outline;
}

Color getCategoryColor(String categoryName) {
  for (final cat in allCategories) {
    if (cat.name.toLowerCase() == categoryName.toLowerCase()) {
      return cat.color;
    }
  }
  return AppColors.highlightPink;
}
