import 'package:flutter/material.dart';

class Worker {
  final String id;
  final String name;
  final String category;
  final List<String> skills;
  final String rating;
  final int reviewsCount;
  final int hunarScore;
  final String location;
  final int pricePerHour;
  final double distanceKm;
  final String experienceYears;
  final String completionRate;
  final String responseTime;
  final IconData profileIcon;
  final String? avatarUrl;
  final bool isVerified;

  const Worker({
    required this.id,
    required this.name,
    required this.category,
    this.skills = const [],
    required this.rating,
    required this.reviewsCount,
    required this.hunarScore,
    required this.location,
    required this.pricePerHour,
    required this.distanceKm,
    required this.experienceYears,
    required this.completionRate,
    required this.responseTime,
    required this.profileIcon,
    this.avatarUrl,
    this.isVerified = false,
  });
}

const mockWorkers = [
  Worker(
    id: 'w1',
    name: 'Sunil Kumar',
    category: 'Home Services',
    skills: ['Plumber', 'Electrician', 'Carpenter', 'Waterproofing'],
    rating: '4.8',
    reviewsCount: 42,
    hunarScore: 94,
    location: 'Hazratganj, Lucknow',
    pricePerHour: 350,
    distanceKm: 1.5,
    experienceYears: '6 Years',
    completionRate: '98%',
    responseTime: '5 Mins',
    profileIcon: Icons.home_repair_service_outlined,
  ),
  Worker(
    id: 'w2',
    name: 'Priya Sharma',
    category: 'Education & Tutoring',
    skills: ['Maths Tutor', 'Science Tutor', 'Primary Class Teacher', 'Urdu Tutor'],
    rating: '4.9',
    reviewsCount: 78,
    hunarScore: 97,
    location: 'Aliganj, Lucknow',
    pricePerHour: 450,
    distanceKm: 3.2,
    experienceYears: '4 Years',
    completionRate: '100%',
    responseTime: '3 Mins',
    profileIcon: Icons.school_outlined,
  ),
  Worker(
    id: 'w3',
    name: 'Aisha Begum',
    category: 'Beauty & Wellness',
    skills: ['Mehendi Artist', 'Makeup Artist', 'Parlour at Home (Ladies)', 'Hair Stylist'],
    rating: '4.7',
    reviewsCount: 120,
    hunarScore: 92,
    location: 'Aminabad, Lucknow',
    pricePerHour: 600,
    distanceKm: 2.1,
    experienceYears: '8 Years',
    completionRate: '95%',
    responseTime: '8 Mins',
    profileIcon: Icons.face_retouching_natural_outlined,
  ),
  Worker(
    id: 'w4',
    name: 'Ramesh Verma',
    category: 'Tailoring & Fashion',
    skills: ['Ladies Tailor (Darzi)', 'Gents Tailor', 'Blouse Stitching', 'Embroidery Artist'],
    rating: '4.6',
    reviewsCount: 35,
    hunarScore: 89,
    location: 'Gomti Nagar, Lucknow',
    pricePerHour: 300,
    distanceKm: 4.0,
    experienceYears: '5 Years',
    completionRate: '94%',
    responseTime: '12 Mins',
    profileIcon: Icons.style_outlined,
  ),
  Worker(
    id: 'w5',
    name: 'Vikram Singh',
    category: 'Food & Catering',
    skills: ['Home Cook (Daily)', 'Tiffin Service', 'Event Catering', 'Tandoor Specialist', 'Biryani Specialist'],
    rating: '4.8',
    reviewsCount: 55,
    hunarScore: 93,
    location: 'Indira Nagar, Lucknow',
    pricePerHour: 400,
    distanceKm: 2.8,
    experienceYears: '7 Years',
    completionRate: '97%',
    responseTime: '6 Mins',
    profileIcon: Icons.restaurant_outlined,
  ),
  Worker(
    id: 'w6',
    name: 'Rohan Mehta',
    category: 'Events & Decoration',
    skills: ['Wedding Decorator', 'Birthday Decorator', 'Balloon Artist', 'DJ / Sound Setup'],
    rating: '4.9',
    reviewsCount: 92,
    hunarScore: 96,
    location: 'Mahanagar, Lucknow',
    pricePerHour: 800,
    distanceKm: 3.5,
    experienceYears: '5 Years',
    completionRate: '99%',
    responseTime: '4 Mins',
    profileIcon: Icons.celebration_outlined,
  ),
  Worker(
    id: 'w7',
    name: 'Dr. Anjali Rao',
    category: 'Health & Fitness',
    skills: ['Yoga Instructor', 'Physiotherapist', 'Nutritionist', 'Meditation Coach'],
    rating: '4.9',
    reviewsCount: 110,
    hunarScore: 98,
    location: 'Jankipuram, Lucknow',
    pricePerHour: 700,
    distanceKm: 4.5,
    experienceYears: '10 Years',
    completionRate: '100%',
    responseTime: '2 Mins',
    profileIcon: Icons.fitness_center_outlined,
  ),
  Worker(
    id: 'w8',
    name: 'Karan Johar',
    category: 'Technology & IT',
    skills: ['Computer Repair', 'Laptop Repair', 'Web Developer', 'App Developer'],
    rating: '4.7',
    reviewsCount: 64,
    hunarScore: 91,
    location: 'Vikas Nagar, Lucknow',
    pricePerHour: 500,
    distanceKm: 2.9,
    experienceYears: '6 Years',
    completionRate: '96%',
    responseTime: '8 Mins',
    profileIcon: Icons.devices_outlined,
  ),
  Worker(
    id: 'w9',
    name: 'Shreya Ghoshal',
    category: 'Pet Care',
    skills: ['Dog Groomer', 'Cat Groomer', 'Pet Sitter', 'Vet at Home'],
    rating: '4.8',
    reviewsCount: 30,
    hunarScore: 94,
    location: 'Hazratganj, Lucknow',
    pricePerHour: 350,
    distanceKm: 1.8,
    experienceYears: '3 Years',
    completionRate: '98%',
    responseTime: '7 Mins',
    profileIcon: Icons.pets_outlined,
  ),
  Worker(
    id: 'w10',
    name: 'Rajesh Pilot',
    category: 'Transport & Logistics',
    skills: ['Personal Driver', 'Truck Driver', 'Auto Driver', 'Packers & Movers'],
    rating: '4.5',
    reviewsCount: 150,
    hunarScore: 88,
    location: 'Charbagh, Lucknow',
    pricePerHour: 250,
    distanceKm: 5.0,
    experienceYears: '12 Years',
    completionRate: '92%',
    responseTime: '15 Mins',
    profileIcon: Icons.local_shipping_outlined,
  ),
  Worker(
    id: 'w11',
    name: 'Harendra Yadav',
    category: 'Agriculture & Rural',
    skills: ['Tractor Operator', 'Crop Advisor', 'Horticulturist', 'Water Pump Repair'],
    rating: '4.6',
    reviewsCount: 40,
    hunarScore: 90,
    location: 'Malihabad, Lucknow',
    pricePerHour: 200,
    distanceKm: 15.0,
    experienceYears: '15 Years',
    completionRate: '95%',
    responseTime: '20 Mins',
    profileIcon: Icons.agriculture_outlined,
  ),
  Worker(
    id: 'w12',
    name: 'Aarav Kumar',
    category: 'Creative & Arts',
    skills: ['Portrait Painter', 'Sketch Artist', 'Madhubani Painter', 'Lippan Art'],
    rating: '4.9',
    reviewsCount: 38,
    hunarScore: 95,
    location: 'Aminabad, Lucknow',
    pricePerHour: 400,
    distanceKm: 2.3,
    experienceYears: '4 Years',
    completionRate: '99%',
    responseTime: '5 Mins',
    profileIcon: Icons.brush_outlined,
  ),
  Worker(
    id: 'w13',
    name: 'Suman Lata',
    category: 'Child Care & Elderly',
    skills: ['Baby Sitter', 'Creche at Home', 'Old Age Care (Female)', 'Patient Attendant'],
    rating: '4.8',
    reviewsCount: 85,
    hunarScore: 96,
    location: 'Aliganj, Lucknow',
    pricePerHour: 300,
    distanceKm: 3.0,
    experienceYears: '8 Years',
    completionRate: '98%',
    responseTime: '6 Mins',
    profileIcon: Icons.child_care_outlined,
  ),
  Worker(
    id: 'w14',
    name: 'Prem Sagar',
    category: 'Construction & Renovation',
    skills: ['Mason / Raj Mistri', 'Welder', 'Plumbing Fitter', 'Electrical Fitter'],
    rating: '4.7',
    reviewsCount: 70,
    hunarScore: 92,
    location: 'Chinhat, Lucknow',
    pricePerHour: 450,
    distanceKm: 6.2,
    experienceYears: '9 Years',
    completionRate: '96%',
    responseTime: '10 Mins',
    profileIcon: Icons.construction_outlined,
  ),
  Worker(
    id: 'w15',
    name: 'Pandit Hari Prasad',
    category: 'Religious & Cultural',
    skills: ['Pandit / Purohit', 'Katha Vachak', 'Bhajan Singer', 'Vastu Expert'],
    rating: '4.9',
    reviewsCount: 140,
    hunarScore: 99,
    location: 'Chowk, Lucknow',
    pricePerHour: 501,
    distanceKm: 3.8,
    experienceYears: '20 Years',
    completionRate: '100%',
    responseTime: '3 Mins',
    profileIcon: Icons.spa_outlined,
  ),
  Worker(
    id: 'w16',
    name: 'Amit Saxena',
    category: 'Technology & IT',
    skills: ['Laptop Repair', 'App Developer', 'Graphic Designer', 'SEO Specialist'],
    rating: '4.6',
    reviewsCount: 28,
    hunarScore: 88,
    location: 'Gomti Nagar, Lucknow',
    pricePerHour: 550,
    distanceKm: 4.2,
    experienceYears: '3 Years',
    completionRate: '93%',
    responseTime: '9 Mins',
    profileIcon: Icons.devices_outlined,
  ),
];
