import 'package:flutter_riverpod/flutter_riverpod.dart';

class LocaleNotifier extends Notifier<String> {
  @override
  String build() => 'ENGLISH';

  void setLocale(String val) {
    state = val;
  }
}

final localeProvider = NotifierProvider<LocaleNotifier, String>(LocaleNotifier.new);

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'ENGLISH': {
      'home': 'HOME',
      'search': 'SEARCH',
      'bookings': 'BOOKINGS',
      'chat': 'CHAT',
      'profile': 'PROFILE',
      'settings': 'SETTINGS',
      'push_notifications': 'PUSH NOTIFICATIONS',
      'dark_mode': 'DARK MODE',
      'language': 'LANGUAGE',
      'location_access': 'LOCATION ACCESS',
      'privacy_mode': 'PRIVACY MODE',
      'help_support': 'HELP & SUPPORT',
      'app_version': 'APP VERSION',
      'delete_account': 'DELETE ACCOUNT',
      'auto_accept_jobs': 'AUTO-ACCEPT JOBS',
      'availability_radius': 'AVAILABILITY RADIUS',
      'show_earnings_publicly': 'SHOW EARNINGS PUBLICLY',
      'edit_profile': 'EDIT PROFILE DETAILS',
      'save_changes': 'SAVE CHANGES',
      'cancel': 'CANCEL',
      'sign_out': 'SIGN OUT',
      'delete': 'DELETE',
      'no_active_bookings': 'NO ACTIVE BOOKINGS YET',
      'no_active_chats': 'NO ACTIVE CHATS YET',
      'location_disabled': 'LOCATION DISABLED',
      'blocked': 'BLOCKED',
      'smart_matches': 'AI SMART MATCHES NEAR YOU',
      'browse_skills': 'BROWSE SKILLS BY CATEGORY',
      'chat_messages': 'CHAT MESSAGES',
      'performance_metrics': 'PERFORMANCE METRICS',
      'upcoming_schedule': 'UPCOMING SCHEDULE',
      'account_info': 'ACCOUNT INFORMATION',
      'partner_profile': 'PARTNER PROFILE',
      'earnings': 'EARNINGS',
      'hunar_score': 'HUNAR SCORE',
      'simulate_booking': 'SIMULATE BOOKING FLOW',
      'simulate_alert_btn': 'SIMULATE REQUEST ALERT',
      'simulate_desc': 'Trigger a simulated customer job request to inspect acceptance and navigation pages.',
      'rating': 'RATING',
      'experience': 'EXPERIENCE',
      'phone': 'PHONE NUMBER',
      'address': 'SERVICE ADDRESS',
      'contact_method': 'PREFERRED CONTACT',
      'preferred_slot': 'PREFERRED SLOT',
      'account_role': 'ACCOUNT ROLE',
      'skill_category': 'SKILL CATEGORY',
      'hourly_rate': 'HOURLY RATE (₹)',
      'location': 'LOCATION',
      'log_out': 'LOGOUT FROM ACCOUNT',
      'try_now': 'TRY NOW',
      'demo_banner_title': 'LIVE SKILL DEMO',
      'demo_banner_desc': 'Request a quick 2-minute video call to inspect work before booking.',
    },
    'HINDI': {
      'home': 'होम',
      'search': 'खोजें',
      'bookings': 'बुकिंग्स',
      'chat': 'चैट',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'push_notifications': 'पुश नोटिफिकेशन',
      'dark_mode': 'डार्क मोड',
      'language': 'भाषा',
      'location_access': 'लोकेशन एक्सेस',
      'privacy_mode': 'प्राइवेसी मोड',
      'help_support': 'सहायता और संपर्क',
      'app_version': 'ऐप वर्शन',
      'delete_account': 'अकाउंट डिलीट करें',
      'auto_accept_jobs': 'ऑटो-एक्सेप्ट जॉब्स',
      'availability_radius': 'उपलब्धता दायरा',
      'show_earnings_publicly': 'कमाई सार्वजनिक दिखाएं',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'save_changes': 'बदलाव सुरक्षित करें',
      'cancel': 'รद्द करें',
      'sign_out': 'साइन आउट',
      'delete': 'डिलीट',
      'no_active_bookings': 'अभी कोई बुकिंग नहीं है',
      'no_active_chats': 'अभी कोई चैट नहीं है',
      'location_disabled': 'लोकेशन बंद है',
      'blocked': 'अवरुद्ध (BLOCKED)',
      'smart_matches': 'आपके आस-पास स्मार्ट मैच',
      'browse_skills': 'श्रेणी अनुसार कौशल ब्राउज़ करें',
      'chat_messages': 'चैट संदेश',
      'performance_metrics': 'प्रदर्शन मेट्रिक्स',
      'upcoming_schedule': 'आगामी अनुसूची',
      'account_info': 'अकाउंट की जानकारी',
      'partner_profile': 'पार्टनर प्रोफ़ाइल',
      'earnings': 'कुल कमाई',
      'hunar_score': 'हुनर स्कोर',
      'simulate_booking': 'सिम्युलेट बुकिंग फ्लो',
      'simulate_alert_btn': 'अनुरोध सिम्युलेट करें',
      'simulate_desc': 'स्वीकृति और नेविगेशन पृष्ठों का निरीक्षण करने के लिए ग्राहक अनुरोध सिम्युलेट करें।',
      'rating': 'रेटिंग',
      'experience': 'अनुभव',
      'phone': 'फ़ोन नंबर',
      'address': 'सेवा का पता',
      'contact_method': 'पसंदीदा संपर्क तरीका',
      'preferred_slot': 'पसंदीदा समय',
      'account_role': 'अकाउंट की भूमिका',
      'skill_category': 'कौशल श्रेणी',
      'hourly_rate': 'प्रति घंटा दर (₹)',
      'location': 'स्थान (लोकेशन)',
      'log_out': 'अकाउंट से लॉगआउट',
      'try_now': 'अभी आज़माएं',
      'demo_banner_title': 'लाइव हुनर डेमो',
      'demo_banner_desc': 'बुकिंग से पहले काम की जांच के लिए 2 मिनट के वीडियो कॉल का अनुरोध करें।',
    },
    'BENGALI': {
      'home': 'হোম',
      'search': 'খুঁজুন',
      'bookings': 'বুকিং',
      'chat': 'চ্যাট',
      'profile': 'প্রোফাইল',
      'settings': 'সেটিংস',
      'push_notifications': 'पुश বিজ্ঞপ্তি',
      'dark_mode': 'ডার্ক মোড',
      'language': 'ভাষা',
      'location_access': 'লোকেশন অ্যাক্সেস',
      'privacy_mode': 'প্রাইভেসি মোড',
      'help_support': 'সহায়তা ও সমর্থন',
      'app_version': 'অ্যাপ সংস্করণ',
      'delete_account': 'অ্যাকাউন্ট মুছুন',
      'auto_accept_jobs': 'স্বয়ংক্রিয় কাজ গ্রহণ',
      'availability_radius': 'উপলব্ধতার ব্যাসার্ধ',
      'show_earnings_publicly': 'উপার্জন প্রকাশ্যে দেখান',
      'edit_profile': 'প্রোফাইল সংশোধন করুন',
      'save_changes': 'পরিবর্তন সংরক্ষণ করুন',
      'cancel': 'বাতিল করুন',
      'sign_out': 'সাইন আউট',
      'delete': 'মুছে ফেলুন',
      'no_active_bookings': 'কোন সক্রিয় বুকিং নেই',
      'no_active_chats': 'কোন সক্রিয় চ্যাট নেই',
      'location_disabled': 'লোকেশন নিষ্ক্রিয়',
      'blocked': 'অবরুদ্ধ',
      'smart_matches': 'আপনার কাছাকাছি スマートマッチ',
      'browse_skills': 'বিভাগ অনুযায়ী দক্ষতা খুঁজুন',
      'chat_messages': 'চ্যাট বার্তা',
      'performance_metrics': 'কর্মক্ষমতা মেট্রিক্স',
      'upcoming_schedule': 'আসন্ন সময়সূচী',
      'account_info': 'অ্যাকাউন্টের তথ্য',
      'partner_profile': 'অংশীদার প্রোফাইল',
      'earnings': 'মোট উপার্জন',
      'hunar_score': 'হুনর স্কোর',
      'simulate_booking': 'সিমুলেট বুকিং প্রবাহ',
      'simulate_alert_btn': 'অনুরোধ সিমুলেট করুন',
      'simulate_desc': 'গ্রহণ এবং নেভিগেশন পৃষ্ঠাগুলি পরীক্ষা করতে গ্রাহক অনুরোধ সিমুলেট করুন।',
      'rating': 'রেটিং',
      'experience': 'অভিজ্ঞতা',
      'phone': 'ফোন নম্বর',
      'address': 'পরিষেবা ঠিকানা',
      'contact_method': 'পছন্দের যোগাযোগ মাধ্যম',
      'preferred_slot': 'পছন্দের সময়',
      'account_role': 'অ্যাকাউন্ট ভূমিকা',
      'skill_category': 'দক্ষতার বিভাগ',
      'hourly_rate': 'ঘণ্টাপ্রতি হার (₹)',
      'location': 'অবস্থান',
      'log_out': 'লগআউট করুন',
      'try_now': 'এখনই চেষ্টা করুন',
      'demo_banner_title': 'লাইভ দক্ষতা ডেমো',
      'demo_banner_desc': 'বুকিং করার আগে কাজ যাচাই করতে ২ মিনিটের ভিডিও কল করুন।',
    },
    'MARATHI': {
      'home': 'होम',
      'search': 'शोधा',
      'bookings': 'बुकिंग्ज',
      'chat': 'चॅट',
      'profile': 'प्रोफाइल',
      'settings': 'सेटिंग्ज',
      'push_notifications': 'पुश अधिसूचना',
      'dark_mode': 'डार्क मोड',
      'language': 'भाषा',
      'location_access': 'लोकेशन ॲक्सेस',
      'privacy_mode': 'प्रायव्हसी मोड',
      'help_support': 'मदत आणि सहाय्य',
      'app_version': 'ॲप आवृत्ती',
      'delete_account': 'खाते हटवा',
      'auto_accept_jobs': 'ऑटो-एक्सेप्ट जॉब्स',
      'availability_radius': 'उपलब्धता त्रिज्या',
      'show_earnings_publicly': 'कमाई सार्वजनिक दाखवा',
      'edit_profile': 'प्रोफाइल संपादित करा',
      'save_changes': 'बदल जतन करा',
      'cancel': 'रद्द करा',
      'sign_out': 'साइन आउट',
      'delete': 'हटवा',
      'no_active_bookings': 'सध्या कोणतीही बुकिंग नाही',
      'no_active_chats': 'सध्या कोणतेही चॅट नाही',
      'location_disabled': 'लोकेशन बंद आहे',
      'blocked': 'ब्लॉक केलेले',
      'smart_matches': 'तुमच्या जवळील स्मार्ट मॅचेस',
      'browse_skills': 'कौशल्यानुसार श्रेणी पहा',
      'chat_messages': 'चॅट संदेश',
      'performance_metrics': 'कामगिरी मेट्रिक्स',
      'upcoming_schedule': 'आगामी वेळापत्रक',
      'account_info': 'खात्याची माहिती',
      'partner_profile': 'पार्टनर प्रोफाइल',
      'earnings': 'एकूण कमाई',
      'hunar_score': 'हुनर स्कोर',
      'simulate_booking': 'सिम्युलेट बुकिंग फ्लो',
      'simulate_alert_btn': 'अनुरोध सिम्युलेट करा',
      'simulate_desc': 'स्वीकृती आणि नेव्हिगेशन पृष्ठे तपासण्यासाठी ग्राहक अनुरोध सिम्युलेट करा।',
      'rating': 'रेटिंग',
      'experience': 'अनुभव',
      'phone': 'फोन नंबर',
      'address': 'सेवेचा पत्ता',
      'contact_method': 'पसंदीदा संपर्क पद्धत',
      'preferred_slot': 'पसंदीदा वेळ',
      'account_role': 'खात्याची भूमिका',
      'skill_category': 'कौशल्य श्रेणी',
      'hourly_rate': 'प्रति तास दर (₹)',
      'location': 'स्थान',
      'log_out': 'खात्यातून लॉगआउट',
      'try_now': 'आता प्रयत्न करा',
      'demo_banner_title': 'लाइव्ह कौशल्य डेमो',
      'demo_banner_desc': 'बुकिंग करण्यापूर्वी कामाची पाहणी करण्यासाठी २ मिनिटांच्या व्हिडिओ कॉलची विनंती करा.',
    },
    'TELUGU': {
      'home': 'హోమ్',
      'search': 'సెర్చ్',
      'bookings': 'బుకింగ్స్',
      'chat': 'చాట్',
      'profile': 'ప్రొఫైల్',
      'settings': 'సెట్టింగ్స్',
      'push_notifications': 'పుష్ నోటిఫికేషన్లు',
      'dark_mode': 'డార్క్ మోడ్',
      'language': 'భాష',
      'location_access': 'location యాక్సెస్',
      'privacy_mode': 'ప్రైవసీ మోడ్',
      'help_support': 'సహాయం & మద్దతు',
      'app_version': 'యాప్ వెర్షన్',
      'delete_account': 'ఖాతా తొలగించు',
      'auto_accept_jobs': 'ఆటో-యాక్సెప్ట్ జాబ్స్',
      'availability_radius': 'లభ్యత వ్యాసార్థం',
      'show_earnings_publicly': 'సంపాదన బహిర్గతం చేయి',
      'edit_profile': 'ప్రొఫైల్ సవరించు',
      'save_changes': 'మార్పులు సేవ్ చేయి',
      'cancel': 'రద్దు చేయి',
      'sign_out': 'సైన్ అవుట్',
      'delete': 'తొలగించు',
      'no_active_bookings': 'యాక్టివ్ బుకింగ్స్ లేవు',
      'no_active_chats': 'యాక్టివ్ చాట్లు లేవు',
      'location_disabled': 'లొకేషన్ డిసేబుల్ చేయబడింది',
      'blocked': 'బ్లాక్ చేయబడింది',
      'smart_matches': 'మీకు దగ్గరలో ఉన్న స్మార్ట్ మ్యాచులు',
      'browse_skills': 'వర్గం వారీగా నైపుణ్యాలు',
      'chat_messages': 'చాట్ సందేశాలు',
      'performance_metrics': 'పనితీరు కొలమానాలు',
      'upcoming_schedule': 'రాబోయే షెడ్యూల్',
      'account_info': 'ఖాతా సమాచారం',
      'partner_profile': 'భాగస్వామి ప్రొఫైల్',
      'earnings': 'మొತ್ತం సంపాదన',
      'hunar_score': 'హునర్ స్కోర్',
      'simulate_booking': 'బుకింగ్ ఫ్లో సిమ్యులేట్ చేయి',
      'simulate_alert_btn': 'అభ్యర్థన సిమ్యులేట్ చేయి',
      'simulate_desc': 'ఆమోదం మరియు నావిగేషన్ పేజీలను పరిశీలించడానికి కస్టమర్ అభ్యర్థనను సిమ్యులేట్ చేయండి.',
      'rating': 'రేటింగ్',
      'experience': 'అనుభవం',
      'phone': 'ఫోన్ నంబర్',
      'address': 'సేవా చిరునామా',
      'contact_method': 'ఇష్టపడే సంప్రదింపు పద్ధతి',
      'preferred_slot': 'ఇష్టపడే సమయం',
      'account_role': 'ఖాతా పాత్ర',
      'skill_category': 'ನೈಪುಣ್ಯ ವರ್ಗ',
      'hourly_rate': 'గంటకు ధర (₹)',
      'location': 'స్థలం',
      'log_out': 'ఖాతా నుండి లాగ్ అవుట్',
      'try_now': 'ఇప్పుడే ప్రయత్నించండి',
      'demo_banner_title': 'లైవ్ నైపుణ్య ప్రదర్శన',
      'demo_banner_desc': 'బుకింగ్ చేయడానికి ముందు పనిని తనిਖీ చేయడానికి క్విక్ 2 నిమిషాల వీడియో కాల్ అడగండి.',
    },
    'TAMIL': {
      'home': 'முகப்பு',
      'search': 'தேடல்',
      'bookings': 'பதிவுகள்',
      'chat': 'அரட்டை',
      'profile': 'சுயவிவரம்',
      'settings': 'அமைப்புகள்',
      'push_notifications': 'புஷ் அறிவிப்புகள்',
      'dark_mode': 'டார்க் மோட்',
      'language': 'மொழி',
      'location_access': 'இருப்பிட அனுமதி',
      'privacy_mode': 'தனியுரிமை முறை',
      'help_support': 'உதவி மற்றும் ஆதரவு',
      'app_version': 'செயலி பதிப்பு',
      'delete_account': 'கணக்கை நீக்கு',
      'auto_accept_jobs': 'தானியங்கி வேலை ஏற்பு',
      'availability_radius': 'கிடைக்கும் ஆரம்',
      'show_earnings_publicly': 'வருமானத்தை பொதுவில் காட்டு',
      'edit_profile': 'சுயவிவரத்தை திருத்து',
      'save_changes': 'மாற்றங்களை சேமி',
      'cancel': 'ரத்துசெய்',
      'sign_out': 'வெளியேறு',
      'delete': 'நீக்கு',
      'no_active_bookings': 'செயலில் உள்ள பதிவுகள் இல்லை',
      'no_active_chats': 'செயலில் உள்ள அரட்டைகள் இல்லை',
      'location_disabled': 'இருப்பிடம் முடக்கப்பட்டது',
      'blocked': 'தடுக்கப்பட்டது',
      'smart_matches': 'உங்களுக்கு அருகிலுள்ள பொருத்தங்கள்',
      'browse_skills': 'பிரிவு வாரியாக திறன்கள்',
      'chat_messages': 'அரட்டை செய்திகள்',
      'performance_metrics': 'செயல்திறன் அளவீடுகள்',
      'upcoming_schedule': 'வரவிருக்கும் அட்டவணை',
      'account_info': 'கணக்கு தகவல்',
      'partner_profile': 'கூட்டாளர் சுயவிவரம்',
      'earnings': 'மொத்த வருமானம்',
      'hunar_score': 'ஹுனர் மதிப்பெண்',
      'simulate_booking': 'பதிவு ஓட்டத்தை உருவகப்படுத்து',
      'simulate_alert_btn': 'வேலை கோரிக்கையை உருவகப்படுத்து',
      'simulate_desc': 'ஏற்பு மற்றும் வழிசெலுத்தல் பக்கங்களை ஆய்வு செய்ய வாடிக்கையாளர் கோரிக்கையை உருவகப்படுத்தவும்.',
      'rating': 'மதிப்பீடு',
      'experience': 'அனுபவம்',
      'phone': 'தொலைபேசி எண்',
      'address': 'சேவை முகவரி',
      'contact_method': 'விருப்பமான தொடர்பு முறை',
      'preferred_slot': 'விருப்பமான நேரம்',
      'account_role': 'கணக்கு பங்கு',
      'skill_category': 'திறன் பிரிவு',
      'hourly_rate': 'மணிநேர கட்டணம் (₹)',
      'location': 'இருப்பிடம்',
      'log_out': 'கணக்கிலிருந்து வெளியேறு',
      'try_now': 'இப்போது முயலுக',
      'demo_banner_title': 'நேரடி திறன் டெமோ',
      'demo_banner_desc': 'பதிவு செய்வதற்கு முன் வேலையைச் சரிபார்க்க 2 நிமிட வீடியோ அழைப்பைக் கேட்கவும்.',
    },
    'GUJARATI': {
      'home': 'હોમ',
      'search': 'શોધ',
      'bookings': 'બુકિંગ્સ',
      'chat': 'ચેટ',
      'profile': 'પ્રોફાઇલ',
      'settings': 'સેટિંગ્સ',
      'push_notifications': 'પુશ સૂચનાઓ',
      'dark_mode': 'ડાર્ક મોડ',
      'language': 'ભાષા',
      'location_access': 'લોકેશન એક્સેસ',
      'privacy_mode': 'પ્રાઇવસી મોડ',
      'help_support': 'મદદ અને સપોર્ટ',
      'app_version': 'એપ વર્ઝન',
      'delete_account': 'ખાતું કાઢી નાખો',
      'auto_accept_jobs': 'ઓટો-એક્સેપ્ટ જોબ્સ',
      'availability_radius': 'ઉપલબ્ધતા ત્રિજ્યા',
      'show_earnings_publicly': 'કમાણી સાર્વજનિક બતાવો',
      'edit_profile': 'પ્રોફાઇલ સુધારો',
      'save_changes': 'ફેરફારો સાચવો',
      'cancel': 'રદ કરો',
      'sign_out': 'સાઇન આઉટ',
      'delete': 'ડિલીટ',
      'no_active_bookings': 'કોઈ સક્રિય બુકિંગ નથી',
      'no_active_chats': 'કોઈ સક્રિય ચેટ નથી',
      'location_disabled': 'લોકેશન બંધ છે',
      'blocked': 'બ્લોક કરેલ',
      'smart_matches': 'તમારી નજીકના સ્માર્ટ મેચો',
      'browse_skills': 'કેટેગરી મુજબ કૌશલ્ય શોધો',
      'chat_messages': 'ચેટ સંદેશાઓ',
      'performance_metrics': 'કામગીરી મેટ્રિક્સ',
      'upcoming_schedule': 'આગામી સમયપત્રક',
      'account_info': 'ખાતાની માહિતી',
      'partner_profile': 'પાર્ટનર પ્રોફાઇલ',
      'earnings': 'કુલ કમાણી',
      'hunar_score': 'હૂનર સ્કોર',
      'simulate_booking': 'બુકિંગ ફ્લો સિમ્યુલેટ કરો',
      'simulate_alert_btn': 'વિનંતી સિમ્યુલેટ કરો',
      'simulate_desc': 'સ્વીકૃતિ અને નેવિગેશન પૃષ્ઠો તપાસવા માટે ગ્રાહક વિનંતી સિમ્યુલેટ કરો.',
      'rating': 'રેટિંગ',
      'experience': 'અનુભવ',
      'phone': 'ફોન નંબર',
      'address': 'સેવાનું સરનામું',
      'contact_method': 'પસંદગીની સંપર્ક પદ્ધતિ',
      'preferred_slot': 'પસંદગીનો સમય',
      'account_role': 'ખાતાની ભૂમિકા',
      'skill_category': 'કૌશલ્ય કેટેગરી',
      'hourly_rate': 'કલાક દીઠ દર (₹)',
      'location': 'સ્થાન',
      'log_out': 'ખાતામાંથી લોગઆઉટ',
      'try_now': 'હમણાં પ્રયત્ન કરો',
      'demo_banner_title': 'લાઈવ ડેમો',
      'demo_banner_desc': 'બુકિંગ કરતા પહેલા કામની ચકાસણી માટે ૨ મિનિટની વિડીયો કોલની વિનંતી કરો.',
    },
    'URDU': {
      'home': 'ہوم',
      'search': 'تلاش',
      'bookings': 'بکنگ',
      'chat': 'چیٹ',
      'profile': 'پروفائل',
      'settings': 'سیٹنگز',
      'push_notifications': 'پش اطلاعات',
      'dark_mode': 'ڈارک موڈ',
      'language': 'زبان',
      'location_access': 'لوکیشن تک رسائی',
      'privacy_mode': 'پرائیویسی موڈ',
      'help_support': 'مدد اور تعاون',
      'app_version': 'ایپ ورژن',
      'delete_account': 'اکاؤنٹ حذف کریں',
      'auto_accept_jobs': 'خودکار کام کی منظوری',
      'availability_radius': 'دستیابی کا دائرہ',
      'show_earnings_publicly': 'کمائی عام دکھائیں',
      'edit_profile': 'پروفائل کی تفصیلات تبدیل کریں',
      'save_changes': 'تبدیلیاں محفوظ کریں',
      'cancel': 'منسوخ کریں',
      'sign_out': 'سائن آؤٹ',
      'delete': 'حذف کریں',
      'no_active_bookings': 'کوئی فعال بکنگ نہیں ہے',
      'no_active_chats': 'کوئی فعال چیٹ نہیں ہے',
      'location_disabled': 'لوکیشن غیر فعال ہے',
      'blocked': 'بلاک شدہ',
      'smart_matches': 'آپ کے قریب بہترین جوڑ',
      'browse_skills': 'زمرہ کے لحاظ سے ہنر تلاش کریں',
      'chat_messages': 'چیٹ پیغامات',
      'performance_metrics': 'کارکردگی کی پیمائش',
      'upcoming_schedule': 'آنے والا شیڈول',
      'account_info': 'اکاؤنٹ کی معلومات',
      'partner_profile': 'شراکت دار پروفائل',
      'earnings': 'کل کمائی',
      'hunar_score': 'ہنر اسکور',
      'simulate_booking': 'بکنگ کا فرضی تجربہ کریں',
      'simulate_alert_btn': 'فرضی درخواست بھیجیں',
      'simulate_desc': 'قبولیت اور نیویگیشن صفحات کا معائنہ کرنے کے لیے گاہک کی فرضی درخواست شروع کریں۔',
      'rating': 'درجہ بندی',
      'experience': 'تجربہ',
      'phone': 'فون نمبر',
      'address': 'سروس کا پتہ',
      'contact_method': 'رابطہ کا پسندیدہ طریقہ',
      'preferred_slot': 'پسندیدہ وقت',
      'account_role': 'اکاؤنٹ کا کردار',
      'skill_category': 'ہنر کا زمرہ',
      'hourly_rate': 'فی گھنٹہ شرح (₹)',
      'location': 'مقام',
      'log_out': 'لاگ آؤٹ کریں',
      'try_now': 'ابھی آزمائیں',
      'demo_banner_title': 'براہ راست ہنر کا مظاہرہ',
      'demo_banner_desc': 'بکنگ سے پہلے کام کی جانچ کے لیے 2 منٹ کی ویڈیو کال کی درخواست کریں۔',
    },
    'KANNADA': {
      'home': 'ಹೋಮ್',
      'search': 'ಹುಡುಕಿ',
      'bookings': 'ಬುಕಿಂಗ್ಸ್',
      'chat': 'ಚಾಟ್',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'push_notifications': 'ಪುಶ್ ನೋಟಿಫಿಕೇಶನ್',
      'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'language': 'ಭಾಷೆ',
      'location_access': 'ಲೊಕೇಶನ್ ಅನುಮತಿ',
      'privacy_mode': 'ಪ್ರೈವೆಸಿ ಮೋಡ್',
      'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
      'app_version': 'ಆಪ್ ಆವೃತ್ತಿ',
      'delete_account': 'ಖಾತೆ ಅಳಿಸಿ',
      'auto_accept_jobs': 'ಸ್ವಯಂ ಉದ್ಯೋಗ ಸ್ವೀಕೃತಿ',
      'availability_radius': 'ಲಭ್ಯತೆಯ ತ್ರಿಜ್ಯ',
      'show_earnings_publicly': 'ಗಳಿಕೆಯನ್ನು ಬಹಿರಂಗಪಡಿಸಿ',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ವಿವರ ತಿದ್ದುಪಡಿ',
      'save_changes': 'ಬದಲಾವಣೆ ಉಳಿಸಿ',
      'cancel': 'ರದ್ದು ಮಾಡಿ',
      'sign_out': 'ಸೈನ್ ಔಟ್',
      'delete': 'ಅಳಿಸಿ',
      'no_active_bookings': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಬುಕಿಂಗ್ ಇಲ್ಲ',
      'no_active_chats': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಚಾಟ್ ಇಲ್ಲ',
      'location_disabled': 'ಲೊಕೇಶನ್ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ',
      'blocked': 'ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ',
      'smart_matches': 'ನಿಮ್ಮ ಹತ್ತಿರದ ಸ್ಮಾರ್ಟ್ ಪಂದ್ಯಗಳು',
      'browse_skills': 'ವರ್ಗದ ಆಧಾರದ ಮೇಲೆ ಕೌಶಲ್ಯ ಹುಡುಕಿ',
      'chat_messages': 'ಚಾಟ್ ಸಂದೇಶಗಳು',
      'performance_metrics': 'ಕಾರ್ಯಕ್ಷಮತೆಯ ಮೆಟ್ರಿಕ್ಸ್',
      'upcoming_schedule': 'ಮುಂಬರುವ ವೇಳಾಪಟ್ಟಿ',
      'account_info': 'ಖಾತೆಯ ಮಾಹಿತಿ',
      'partner_profile': 'ಪಾಲುದಾರ ಪ್ರೊಫైಲ್',
      'earnings': 'ಒಟ್ಟು ಗಳಿಕೆ',
      'hunar_score': 'ಹುನರ್ ಸ್ಕೋರ್',
      'simulate_booking': 'ಬುಕಿಂಗ್ ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ',
      'simulate_alert_btn': 'ಕೋರಿಕೆ ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ',
      'simulate_desc': 'ಸ್ವೀಕೃತಿ ಮತ್ತು ಸಂಚರಣೆ ಪುಟಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಗ್ರಾಹಕರ ವಿನಂತಿಯನ್ನು ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ.',
      'rating': 'ರೇಟಿಂಗ್',
      'experience': 'ಅನುಭವ',
      'phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      'address': 'ಸೇವೆಯ ವಿಳಾಸ',
      'contact_method': 'ಸಂಪರ್ಕದ ಆದ್ಯತೆಯ ವಿಧಾನ',
      'preferred_slot': 'ಆದ್ಯತೆಯ ಸಮಯ',
      'account_role': 'ಖಾತೆಯ ಪಾತ್ರ',
      'skill_category': 'ಕೌಶಲ್ಯದ ವರ್ಗ',
      'hourly_rate': 'ಗಂಟೆಯ ದರ (₹)',
      'location': 'ಸ್ಥಳ',
      'log_out': 'ಖಾತೆಯಿಂದ ಲಾಗ್ ಔಟ್',
      'try_now': 'ಈಗಲೇ ಪ್ರಯತ್ನಿಸಿ',
      'demo_banner_title': 'ಲೈವ್ ಕೌಶಲ್ಯ ಡೆಮೋ',
      'demo_banner_desc': 'ಬುಕಿಂಗ್ ಮಾಡುವ ಮೊದಲು ಕೆಲಸವನ್ನು ಪರಿಶೀಲಿಸಲು 2 ನಿಮಿಷಗಳ ವೀಡಿಯೊ ಕರೆಗೆ ವಿನಂತಿಸಿ.',
    },
    'PUNJABI': {
      'home': 'ਹੋਮ',
      'search': 'ਖੋਜੋ',
      'bookings': 'ਬੁਕਿੰਗਸ',
      'chat': 'ਚੈਟ',
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'settings': 'ਸੈਟਿੰਗਜ਼',
      'push_notifications': 'ਪੁਸ਼ ਨੋਟੀਫਿਕੇਸ਼ਨ',
      'dark_mode': 'ਡਾਰਕ ਮੋਡ',
      'language': 'ਭਾਸ਼ਾ',
      'location_access': 'ਲੋਕੇਸ਼ਨ ਪਹੁੰਚ',
      'privacy_mode': 'ਪ੍ਰਾਈਵੇਸੀ ਮੋਡ',
      'help_support': 'ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ',
      'app_version': 'ਐਪ ਵਰਜ਼ਨ',
      'delete_account': 'ਖਾਤਾ ਮਿਟਾਓ',
      'auto_accept_jobs': 'ਆਟੋ-ਐਕਸੈਪਟ ਜੋਬਸ',
      'availability_radius': 'ਉਪਲਬਧਤਾ ਦਾ ਘੇਰਾ',
      'show_earnings_publicly': 'ਕਮਾਈ ਜਨਤਕ ਦਿਖਾਓ',
      'edit_profile': 'ਪ੍ਰੋਫਾਈਲ ਸੋਧੋ',
      'save_changes': 'ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'sign_out': 'ਸਾਈਨ ਆਊਟ',
      'delete': 'ਮਿਟਾਓ',
      'no_active_bookings': 'ਕੋਈ ਸਰਗਰਮ ਬੁਕਿੰਗ ਨਹੀਂ',
      'no_active_chats': 'ਕੋਈ ਸਰਗਰਮ ਚੈਟ ਨਹੀਂ',
      'location_disabled': 'ਲੋਕੇਸ਼ਨ ਬੰਦ ਹੈ',
      'blocked': 'ਬਲਾਕ ਕੀਤਾ ਗਿਆ',
      'smart_matches': 'ਤੁਹਾਡੇ ਨੇੜੇ ਦੇ ਸਮਾਰਟ ਮੈਚ',
      'browse_skills': 'ਸ਼੍ਰੇਣੀ ਅਨੁਸਾਰ ਹੁਨਰ ਦੇਖੋ',
      'chat_messages': 'ਚੈਟ ਸੁਨੇਹੇ',
      'performance_metrics': 'ਕਾਰਗੁਜ਼ਾਰੀ ਮੈਟ੍ਰਿਕਸ',
      'upcoming_schedule': 'ਆਉਣ ਵਾਲਾ ਸਮਾਂ-ਸਾਰਣੀ',
      'account_info': 'ਖਾਤੇ ਦੀ ਜਾਣਕਾਰੀ',
      'partner_profile': 'ਭਾਗੀਦਾਰ ਪ੍ਰੋਫਾਈਲ',
      'earnings': 'ਕੁੱਲ ਕਮਾਈ',
      'hunar_score': 'ਹੁਨਰ ਸਕੋਰ',
      'simulate_booking': 'ਬੁਕਿੰਗ ਫਲੋ ਸਿਮੂਲੇਟ ਕਰੋ',
      'simulate_alert_btn': 'ਬੇਨਤੀ ਸਿਮੂਲੇਟ ਕਰੋ',
      'simulate_desc': 'ਮਨਜ਼ੂਰੀ ਅਤੇ ਨੇਵੀਗੇਸ਼ਨ ਪੰਨਿਆਂ ਦੀ ਜਾਂਚ ਕਰਨ ਲਈ ਗਾਹਕ ਦੀ ਬੇਨਤੀ ਨੂੰ ਸਿਮੂਲੇਟ ਕਰੋ।',
      'rating': 'ਰੇਟਿੰਗ',
      'experience': 'ਤਜਰਬਾ',
      'phone': 'ਫ਼ੋਨ ਨੰਬਰ',
      'address': 'ਸੇਵਾ ਦਾ ਪਤਾ',
      'contact_method': 'ਪਸੰਦੀਦਾ ਸੰਪਰਕ ਤਰੀਕਾ',
      'preferred_slot': 'ਪਸੰਦੀਦਾ ਸਮਾਂ',
      'account_role': 'ਖਾਤੇ ਦਾ ਰੋਲ',
      'skill_category': 'ਹੁਨਰ ਦੀ ਸ਼੍ਰੇਣੀ',
      'hourly_rate': 'ਪ੍ਰਤੀ ਘੰਟਾ ਦਰ (₹)',
      'location': 'ਟਿਕਾਣਾ',
      'log_out': 'ਖਾਤੇ ਤੋਂ ਲੌਗਆਊਟ',
      'try_now': 'ਹੁਣੇ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      'demo_banner_title': 'ਲਾਈਵ ਹੁਨਰ ਡੈਮો',
      'demo_banner_desc': 'ਬੁਕਿੰਗ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਕੰਮ ਦੀ ਜਾਂਚ ਲਈ 2 ਮਿੰਟ ਦੀ ਵੀਡੀਓ ਕਾਲ ਦੀ ਬੇਨਤੀ ਕਰੋ।',
    },
    'MALAYALAM': {
      'home': 'ഹോം',
      'search': 'തിരയുക',
      'bookings': 'ബുക്കിംഗുകൾ',
      'chat': 'ചാറ്റ്',
      'profile': 'പ്രൊഫൈൽ',
      'settings': 'സെറ്റിംഗ്സ്',
      'push_notifications': 'പുഷ് അറിയിപ്പുകൾ',
      'dark_mode': 'ഡാർക്ക് മോഡ്',
      'language': 'ഭാഷ',
      'location_access': 'ലൊക്കേഷൻ അനുമതി',
      'privacy_mode': 'സ്വകാര്യതാ മോഡ്',
      'help_support': 'സഹായവും പിന്തുണയും',
      'app_version': 'ആപ്പ് പതിപ്പ്',
      'delete_account': 'അക്കൗണ്ട് ഇല്ലാതാക്കുക',
      'auto_accept_jobs': 'തനിയെ ജോലി സ്വീകരിക്കൽ',
      'availability_radius': 'പരിധി വ്യാസാർദ്ധം',
      'show_earnings_publicly': 'വരുമാനം പരസ്യമാക്കുക',
      'edit_profile': 'പ്രൊഫൈൽ തിരുത്തുക',
      'save_changes': 'മാറ്റങ്ങൾ സൂക്ഷിക്കുക',
      'cancel': 'റദ്ദാക്കുക',
      'sign_out': 'സൈൻ ഔട്ട്',
      'delete': 'ഡിലീറ്റ്',
      'no_active_bookings': 'സജീവമായ ബുക്കിംഗുകൾ ഇല്ല',
      'no_active_chats': 'സജീവമായ ചാറ്റുകൾ ഇല്ല',
      'location_disabled': 'ലൊക്കേഷൻ പ്രവർത്തനരഹിതമാക്കി',
      'blocked': 'തടയപ്പെട്ടു',
      'smart_matches': 'നിങ്ങളുടെ അടുത്തുള്ള മാച്ചുകൾ',
      'browse_skills': 'വിഭാഗം തിരിച്ചുള്ള സേവനങ്ങൾ',
      'chat_messages': 'ചാറ്റ് സന്ദേശങ്ങൾ',
      'performance_metrics': 'പ്രകടന നിലവാരം',
      'upcoming_schedule': 'വരാനിരിക്കുന്ന വിവരങ്ങൾ',
      'account_info': 'അക്കൗണ്ട് വിവരങ്ങൾ',
      'partner_profile': 'പങ്കാളി പ്രൊഫൈൽ',
      'earnings': 'ആകെ വരുമാനം',
      'hunar_score': 'ഹുനർ സ്കോർ',
      'simulate_booking': 'ಬುಕ್ಕിംഗ് സിമുലേഷൻ',
      'simulate_alert_btn': 'താല്ക്കാലിക ബുക്കിംഗ് നൽകുക',
      'simulate_desc': 'സ്വീകാര്യതയും റൂട്ടുകളും പരിശോധിക്കാൻ താൽക്കാലിക ബുക്കിംഗ് നൽകുക.',
      'rating': 'റേറ്റിംഗ്',
      'experience': 'പ്രവൃത്തിപരിചയം',
      'phone': 'ഫോൺ നമ്പർ',
      'address': 'സേവന വിലാസം',
      'contact_method': 'ബന്ധപ്പെടേണ്ട രീതി',
      'preferred_slot': 'അനുയോജ്യമായ സമയം',
      'account_role': 'അക്കൗണ്ട് റോൾ',
      'skill_category': 'സേവന വിഭാഗം',
      'hourly_rate': 'മണിക്കൂർ നിരക്ക് (₹)',
      'location': 'സ്ഥലം',
      'log_out': 'ലോഗ് ഔട്ട് ചെയ്യുക',
      'try_now': 'ഇപ്പോൾ ശ്രമിക്കുക',
      'demo_banner_title': 'നേരിട്ടുള്ള കൗശല ഡെമോ',
      'demo_banner_desc': 'ബുക്ക് ചെയ്യുന്നതിന് മുൻപ് ജോലി വിലയിരുത്താൻ 2 മിനിറ്റ് വീഡിയോ കോൾ ചെയ്യാം.',
    },
    'ODIA': {
      'home': 'ହୋମ',
      'search': 'ଖୋଜନ୍ତୁ',
      'bookings': 'ଖାତା',
      'chat': 'ଚାଟ',
      'profile': 'ପ୍ରୋଫାଇଲ',
      'settings': 'ସେଟିଙ୍ଗସ',
      'push_notifications': 'ପୁସ ନୋଟିଫିକେସନ',
      'dark_mode': 'ଡାର୍କ ମୋଡ',
      'language': 'ଭାଷା',
      'location_access': 'ଲୋକେସନ ଅନୁମତି',
      'privacy_mode': 'ପ୍ରାଇଭେସି ମୋଡ',
      'help_support': 'ସହାୟତା ଓ ସମ୍ପର୍କ',
      'app_version': 'ଆପ ସଂସ୍କରଣ',
      'delete_account': 'ଖାତା ବନ୍ଦ କରନ୍ତು',
      'auto_accept_jobs': 'ସ୍ୱୟଂଚାଳିତ କାର୍ଯ୍ୟ ସ୍ୱୀକୃତି',
      'availability_radius': 'ଉପଲବ୍ଧତା ସୀମା',
      'show_earnings_publicly': 'ଆୟ ସାର୍ବଜନୀନ କରନ୍ତು',
      'edit_profile': 'ପ୍ରୋଫାଇଲ ସଂଶୋਧନ',
      'save_changes': 'ପରିବର୍ତ୍තନ ସାଇତି ରଖନ୍ତು',
      'cancel': 'ବାତିଲ କରନ୍ତು',
      'sign_out': 'ସାଇନ ଆଉਟ',
      'delete': 'ଲିଭାନ୍ତু',
      'no_active_bookings': 'କୌଣସି ବୁକିଂ ନାହିଁ',
      'no_active_chats': 'କୌଣସି ଚାଟ ନାହିଁ',
      'location_disabled': 'ଲୋକେସନ ବନ୍ଦ ଅଛି',
      'blocked': 'ଅବରୋଧିତ',
      'smart_matches': 'ଆପଣଙ୍କ ନିକଟବର୍ତ୍ତୀ ମ୍ୟାଚ',
      'browse_skills': 'ଶ୍ରେଣୀ ଅନୁଯାୟୀ କୌଶଳ',
      'chat_messages': 'ଚାଟ ବାର୍ତ୍ତା',
      'performance_metrics': 'କାର୍ଯ୍ୟଦକ୍ଷତା ମାପଦଣ୍ڈ',
      'upcoming_schedule': 'ଆଗାମୀ କାର୍ଯ್ಯସୂଚୀ',
      'account_info': 'ଖାତାର ବିବରଣီ',
      'partner_profile': 'ଅଂଶୀଦାର ପ୍ରୋଫਾਈଲ',
      'earnings': 'ମୋਟ ଆୟ',
      'hunar_score': 'ହୁନର ସ୍କୋਰ',
      'simulate_booking': 'ବୁକିଂ ପ୍ରକ୍ରିୟା ଅନୁକରଣ',
      'simulate_alert_btn': 'ଅନୁରୋধ ପଠାନ୍ତು',
      'simulate_desc': 'କାର୍ଯ୍ୟ ସ୍ୱୀକୃତି ଯାଞ୍ચ କରିବାକୁ ଗ୍ରାହକ ଅନುରୋଧ ଅନୁକରଣ କରନ୍ତు।',
      'rating': 'ରେଟିଙ୍ग',
      'experience': 'ଅଭିଜ୍ଞତା',
      'phone': 'ଫୋନ ନମ୍ବਰ',
      'address': 'ସେବା ପ୍ରଦାନ ସ୍ଥាន',
      'contact_method': 'ଯୋਗาଯୋଗର ମାଧ୍ୟମ',
      'preferred_slot': 'ପସନ୍ଦର ସମୟ',
      'account_role': 'ଖାତାର ଭୂମିକา',
      'skill_category': 'କୌଶଳ ଶ୍ରେଣୀ',
      'hourly_rate': 'ଘଣ୍ଟା ପ୍ରତି ମୂଲ୍ୟ (₹)',
      'location': 'ସ୍ଥାନ',
      'log_out': 'ଲଗଆଉଟ କରନ୍ତು',
      'try_now': 'ଏବେ ଚେଷ୍ଟା କରନ୍ତು',
      'demo_banner_title': 'ଲାଇଭ କୌଶଳ ଡେମୋ',
      'demo_banner_desc': 'ବୁକིଂ ପୂର୍ବରୁ କାਮ ଦେଖିବା ପାଇଁ ୨ ମିନିଟର ଭିଡିଓ କଲ କରନ୍ତು।',
    }
  };

  static String translate(String key, String locale) {
    final values = _localizedValues[locale.toUpperCase()] ?? _localizedValues['ENGLISH']!;
    return values[key] ?? key.toUpperCase();
  }

  static final Map<String, List<String>> stateLanguages = {
    'Andhra Pradesh': ['Telugu', 'Urdu', 'Hindi', 'Tamil', 'Kannada'],
    'Arunachal Pradesh': ['Nyishi', 'Adi', 'Bengali', 'Nepali', 'Hindi', 'English'],
    'Assam': ['Assamese', 'Bengali', 'Bodo', 'Hindi', 'Nepali'],
    'Bihar': ['Hindi', 'Maithili', 'Bhojpuri', 'Magahi', 'Vajjika'],
    'Chhattisgarh': ['Hindi', 'Chhattisgarhi', 'Gondi', 'Halbi', 'Odia'],
    'Goa': ['Konkani', 'Marathi', 'Hindi', 'English', 'Kannada'],
    'Gujarat': ['Gujarati', 'Hindi', 'Urdu', 'Sindhi', 'Kutchi'],
    'Haryana': ['Hindi', 'Haryanvi', 'Punjabi', 'Urdu'],
    'Himachal Pradesh': ['Hindi', 'Pahari', 'Kangri', 'Dogri', 'Kinnauri'],
    'Jharkhand': ['Hindi', 'Santali', 'Bengali', 'Mundari', 'Ho', 'Kurukh'],
    'Karnataka': ['Kannada', 'Urdu', 'Telugu', 'Hindi', 'Tamil', 'Tulu'],
    'Kerala': ['Malayalam', 'Tamil', 'Kannada', 'Tulu', 'Hindi'],
    'Madhya Pradesh': ['Hindi', 'Bundeli', 'Malvi', 'Nimadi', 'Gondi'],
    'Maharashtra': ['Marathi', 'Hindi', 'Urdu', 'Gujarati', 'Konkani'],
    'Manipur': ['Meitei (Manipuri)', 'Tangkhul', 'Hindi', 'Bengali'],
    'Meghalaya': ['Khasi', 'Garo', 'Bengali', 'Hindi', 'English'],
    'Mizoram': ['Mizo', 'Bengali', 'Hindi', 'English'],
    'Nagaland': ['Nagamese', 'Ao', 'Lotha', 'Sumi', 'Hindi', 'English'],
    'Odisha': ['Odia', 'Hindi', 'Bengali', 'Santali', 'Telugu'],
    'Punjab': ['Punjabi', 'Hindi', 'Urdu'],
    'Rajasthan': ['Hindi', 'Rajasthani', 'Marwari', 'Shekhawati', 'Mewari'],
    'Sikkim': ['Nepali', 'Sikkimese', 'Lepcha', 'Hindi', 'English'],
    'Tamil Nadu': ['Tamil', 'Telugu', 'Kannada', 'Urdu', 'Malayalam'],
    'Telangana': ['Telugu', 'Urdu', 'Hindi', 'Marathi', 'Lambadi'],
    'Tripura': ['Bengali', 'Kokborok', 'Hindi', 'Manipuri'],
    'Uttar Pradesh': ['Hindi', 'Urdu', 'Awadhi', 'Bhojpuri', 'Braj Bhasha'],
    'Uttarakhand': ['Hindi', 'Garhwali', 'Kumaoni', 'Urdu', 'Punjabi'],
    'West Bengal': ['Bengali', 'Hindi', 'Urdu', 'Santali', 'Nepali'],
    'Andaman & Nicobar Islands': ['Bengali', 'Hindi', 'Tamil', 'Telugu', 'Nicobari'],
    'Chandigarh': ['Hindi', 'Punjabi', 'Urdu'],
    'D&N Haveli & Daman & Diu': ['Gujarati', 'Hindi', 'Marathi'],
    'Delhi (NCT)': ['Hindi', 'Punjabi', 'Urdu', 'Bengali', 'Maithili'],
    'Jammu & Kashmir': ['Kashmiri', 'Dogri', 'Hindi', 'Urdu', 'Punjabi'],
    'Ladakh': ['Ladakhi', 'Hindi', 'Urdu', 'Balti', 'Shina'],
    'Lakshadweep': ['Malayalam', 'Hindi'],
    'Puducherry': ['Tamil', 'Telugu', 'Malayalam', 'French', 'Hindi'],
  };

  static String getFallbackLocale(String language) {
    final lang = language.toUpperCase().trim();
    const supported = {
      'ENGLISH', 'HINDI', 'BENGALI', 'MARATHI', 'TELUGU', 'TAMIL', 'GUJARATI', 'URDU', 'KANNADA', 'PUNJABI', 'MALAYALAM', 'ODIA'
    };
    if (supported.contains(lang)) {
      return lang;
    }
    if (const ['MAITHILI', 'BHOJPURI', 'MAGAHI', 'VAJJIKA', 'CHHATTISGARHI', 'GONDI', 'HALBI', 'HARYANVI', 'PAHARI', 'KANGRI', 'DOGRI', 'KINNAURI', 'BUNDELI', 'MALVI', 'NIMADI', 'RAJASTHANI', 'MARWARI', 'SHEKHAWATI', 'MEWARI', 'AWADHI', 'BRAJ BHASHA', 'GARHWALI', 'KUMAONI', 'NEPALI'].contains(lang)) {
      return 'HINDI';
    }
    if (const ['ASSAMESE', 'BODO', 'MEITEI (MANIPURI)', 'MANIPURI', 'TANGKHUL', 'KOKBOROK', 'SANTALI'].contains(lang)) {
      return 'BENGALI';
    }
    if (const ['KONKANI'].contains(lang)) {
      return 'MARATHI';
    }
    if (const ['SINDHI', 'KUTCHI'].contains(lang)) {
      return 'GUJARATI';
    }
    if (const ['TULU'].contains(lang)) {
      return 'KANNADA';
    }
    if (const ['LAMBADI'].contains(lang)) {
      return 'TELUGU';
    }
    if (const ['KASHMIRI'].contains(lang)) {
      return 'URDU';
    }
    return 'ENGLISH';
  }
}

